highlighter: pygments
markdown: kramdown
gems:
  - jekyll-redirect-from

# For some reason kramdown seems to behave differently on different
# OS/packages wrt encoding. So we hard code this config.
kramdown:
  entity_output: numeric

include:
  - _static
  - _modules

# These allow the documentation to be updated with newer releases
# of Spark, Scala, and Mesos.
<<<<<<< HEAD
SPARK_VERSION: 2.2.2-SNAPSHOT
SPARK_VERSION_SHORT: 2.2.2
SCALA_BINARY_VERSION: "2.11"
SCALA_VERSION: "2.11.8"
=======
SPARK_VERSION: 2.4.1-SNAPSHOT
SPARK_VERSION_SHORT: 2.4.1
SCALA_BINARY_VERSION: "2.11"
SCALA_VERSION: "2.11.12"
>>>>>>> master
MESOS_VERSION: 1.0.0
SPARK_ISSUE_TRACKER_URL: https://issues.apache.org/jira/browse/SPARK
SPARK_GITHUB_URL: https://github.com/apache/spark
